### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by karbassi** [bsdelf/statbar#1]
Hello @bsdelf,

This seems like a great open-source project that could replace the basic functions of [iStat Menus](https://bjango.com/mac/istatmenus/). Good stuff! 👍 

I looked in the releases and I couldn't find a build. Could you provide a build or instructions?

**Comment by bsdelf** [comment]
For pre-built binary package, check release [v1.2.3](https://github.com/bsdelf/statbar/releases/tag/v1.2.3).

To build this application, you need to install Xcode from AppStore.

Note: macOS 10.11+ is a hard requirement.
